### ISSUE TITLE
Switch Input

### ISSUE THREAD

**Issue by ghost** [tyoung3/BlinkLight#2]
Under 'Blink a light when this contact opens or closes', I don't have the option to use my Fibaro dimmer switch input, but can chose it as a light to flash.
My motion sensors are coming up as expected but required for my application
Is there something I'm missing?

**Comment by tyoung3** [comment]
Light should blink when motion is detected or if a contact is opened or closed. So if your light blinks when motion is detected you are all set. 

De twy
